In [2]:
import pandas as pd

import os

In [4]:

genuine = pd.read_csv(os.path.join(DATA_PATH, "genuine_accounts/users.csv"))

print("Genuine accounts shape:", genuine.shape)

genuine.head()

Genuine accounts shape: (3474, 42)

,id,name,screen_name,statuses_count,followers_count,friends_count,favourites_count,listed_count,url,lang,...,notifications,description,contributors_enabled,following,created_at,timestamp,crawled_at,updated,test_set_1,test_set_2
0,1502026416,TASUKU HAYAKAWA,0918Bask,2177,208,332,265,1,NaN,ja,...,NaN,15years ago X.Lines24,NaN,NaN,Tue Jun 11 11:20:35 +0000 2013,2013-06-11 13:20:35,2015-05-02 06:41:46,2016-03-15 15:53:47,0,0
1,2492782375,ro_or,1120Roll,2660,330,485,3972,5,NaN,ja,...,NaN,保守見習い地元大好き人間。 経済学、電工、仏教を勉強中、ちなDeではいかんのか？ (*^◯^*),NaN,NaN,Tue May 13 10:37:57 +0000 2014,2014-05-13 12:37:57,2015-05-01 17:20:27,2016-03-15 15:53:48,0,0
2,293212315,bearclaw,14KBBrown,1254,166,177,1185,0,NaN,en,...,NaN,Let me see what your best move is!,NaN,NaN,Wed May 04 23:30:37 +0000 2011,2011-05-05 01:30:37,2015-05-01 18:48:28,2016-03-15 15:53:48,0,0
3,191839658,pocahontas farida,wadespeters,202968,2248,981,60304,101,http://t.co/rGV0HIJGsu,en,...,NaN,20. menna: #farida #nyc and the 80s actually y...,NaN,NaN,Fri Sep 17 14:02:10 +0000 2010,2010-09-17 16:02:10,2015-05-01 13:55:16,2016-03-15 15:53:48,0,0
4,3020965143,Ms Kathy,191a5bd05da04dc,82,21,79,5,0,NaN,en,...,NaN,Cosmetologist,NaN,NaN,Fri Feb 06 04:10:49 +0000 2015,2015-02-06 05:10:49,2015-05-02 01:17:32,2016-03-15 15:53:48,0,0

In [5]:
social_spambots_1 = pd.read_csv(os.path.join(DATA_PATH, "social_spambots_1/users.csv"))
social_spambots_2 = pd.read_csv(os.path.join(DATA_PATH, "social_spambots_2/users.csv"))
social_spambots_3 = pd.read_csv(os.path.join(DATA_PATH, "social_spambots_3/users.csv"))
traditional_spambots_1 = pd.read_csv(os.path.join(DATA_PATH, "traditional_spambots_1/users.csv"))
fake_followers = pd.read_csv(os.path.join(DATA_PATH, "fake_followers/users.csv"))

print("Social spambots 1:", social_spambots_1.shape)
print("Social spambots 2:", social_spambots_2.shape)
print("Social spambots 3:", social_spambots_3.shape)
print("Traditional spambots 1:", traditional_spambots_1.shape)
print("Fake followers:", fake_followers.shape)

Social spambots 1: (991, 41)
Social spambots 2: (3457, 40)
Social spambots 3: (464, 41)
Traditional spambots 1: (1000, 40)
Fake followers: (3351, 38)

In [9]:


df.describe()

,id,statuses_count,followers_count,friends_count,favourites_count,listed_count,default_profile,default_profile_image,geo_enabled,profile_use_background_image,...,is_translator,follow_request_sent,protected,verified,notifications,contributors_enabled,following,test_set_1,test_set_2,label
count,1.273700e+04,12737.000000,12737.000000,12737.000000,12737.000000,12737.000000,4404.0,66.0,2346.0,11332.0,...,1.0,0.0,78.0,11.0,0.0,0.0,0.0,4465.000000,3938.000000,12737.000000
mean,1.170702e+09,5240.223601,670.595509,601.674492,1290.638141,6.806705,1.0,1.0,1.0,1.0,...,1.0,NaN,1.0,1.0,NaN,NaN,NaN,0.445913,0.242255,0.727251
std,9.540452e+08,18039.397020,10028.652009,1704.464824,6396.370455,89.234947,0.0,0.0,0.0,0.0,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.497122,0.428502,0.445390
min,6.780330e+05,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0,1.0,1.0,...,1.0,NaN,1.0,1.0,NaN,NaN,NaN,0.000000,0.000000,0.000000
25%,3.317998e+08,34.000000,6.000000,42.000000,0.000000,0.000000,1.0,1.0,1.0,1.0,...,1.0,NaN,1.0,1.0,NaN,NaN,NaN,0.000000,0.000000,0.000000
50%,7.275804e+08,64.000000,18.000000,240.000000,0.000000,0.000000,1.0,1.0,1.0,1.0,...,1.0,NaN,1.0,1.0,NaN,NaN,NaN,0.000000,0.000000,1.000000
75%,2.354779e+09,1812.000000,297.000000,576.000000,47.000000,1.000000,1.0,1.0,1.0,1.0,...,1.0,NaN,1.0,1.0,NaN,NaN,NaN,1.000000,0.000000,1.000000
max,3.164942e+09,399555.000000,986837.000000,90861.000000,313954.000000,6166.000000,1.0,1.0,1.0,1.0,...,1.0,NaN,1.0,1.0,NaN,NaN,NaN,1.000000,1.000000,1.000000

In [10]:
df.groupby("label")[[
    "statuses_count",
    "followers_count", 
    "friends_count",
    "favourites_count",
    "listed_count"
]].mean().round(1)

,statuses_count,followers_count,friends_count,favourites_count,listed_count
label,,,,,
0,16958.2,1393.2,633.2,4669.6,19.5
1,845.5,399.6,589.8,23.4,2.0

In [6]:

genuine["label"] = 0

social_spambots_1["label"] = 1
social_spambots_2["label"] = 1
social_spambots_3["label"] = 1
traditional_spambots_1["label"] = 1
fake_followers["label"] = 1


df = pd.concat([
    genuine,
    social_spambots_1,
    social_spambots_2,
    social_spambots_3,
    traditional_spambots_1,
    fake_followers
], ignore_index=True)

print("Combined dataset shape:", df.shape)
print("\nLabel breakdown:")

print(df["label"].value_counts())

Combined dataset shape: (12737, 43)

Label breakdown:
label
1    9263
0    3474
Name: count, dtype: int64

In [7]:
print("Columns available:")
for col in df.columns:
    print(" -", col)

Columns available:
 - id
 - name
 - screen_name
 - statuses_count
 - followers_count
 - friends_count
 - favourites_count
 - listed_count
 - url
 - lang
 - time_zone
 - location
 - default_profile
 - default_profile_image
 - geo_enabled
 - profile_image_url
 - profile_banner_url
 - profile_use_background_image
 - profile_background_image_url_https
 - profile_text_color
 - profile_image_url_https
 - profile_sidebar_border_color
 - profile_background_tile
 - profile_sidebar_fill_color
 - profile_background_image_url
 - profile_background_color
 - profile_link_color
 - utc_offset
 - is_translator
 - follow_request_sent
 - protected
 - verified
 - notifications
 - description
 - contributors_enabled
 - following
 - created_at
 - timestamp
 - crawled_at
 - updated
 - test_set_1
 - test_set_2
 - label

In [8]:
missing = df.isnull().sum()

print("Columns with missing values:")
print(missing[missing > 0])

Columns with missing values:
name                                      1
url                                   10689
lang                                   1000
time_zone                              8707
location                               6541
default_profile                        8333
default_profile_image                 12671
geo_enabled                           10391
profile_banner_url                     9371
profile_use_background_image           1405
profile_background_image_url_https     1000
profile_text_color                     1000
profile_image_url_https                1000
profile_sidebar_border_color           1000
profile_background_tile                7316
profile_sidebar_fill_color             1000
profile_background_color               1000
profile_link_color                     1000
utc_offset                             8707
is_translator                         12736
follow_request_sent                   12737
protected                             12659
verified                              12726
notifications                         12737
description                            5726
contributors_enabled                  12737
following                             12737
timestamp                              3351
crawled_at                             3351
test_set_1                             8272
test_set_2                             8799
dtype: int64

In [3]:
DATA_PATH = "../data"

for item in os.listdir(DATA_PATH):
    print(item)

crowdflower_results
fake_followers
genuine_accounts
social_spambots_1
social_spambots_2
social_spambots_3
traditional_spambots_1
traditional_spambots_2
traditional_spambots_3
traditional_spambots_4

In [1]:
! pip install pandas

Requirement already satisfied: pandas in C:\Users\SEKINA\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\SEKINA\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\SEKINA\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\SEKINA\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\SEKINA\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip